In [1]:
import tensorflow as tf

In [180]:
import numpy as np

# Creating tensors from existing constants

In [18]:
matrix = tf.constant([
    [10, 7, 0],
    [0, 7, 10]
])

matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  0],
       [ 0,  7, 10]], dtype=int32)>

In [177]:
print(matrix.ndim)

new_matrix = tf.constant([
    [
        [1,2,3],
        [3,4,5]
    ],
    [
        [7,8,9],
        [10,11,12,]
    ]
])

new_matrix.shape, matrix.shape

2


(TensorShape([2, 2, 3]), TensorShape([2, 3]))

In [17]:
magic_num = tf.Variable([69., 89.])
magic_num_2 = tf.constant([69., 87,])

magic_num, magic_num_2

(<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([69., 89.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([69., 87.], dtype=float32)>)

# Random Tensors

### What is random seed?
The random data generated is actually pseudo-random i.e for some seed X, the random data generated of a specific shape will always be the same.

This comes in handy when we want to reproduce the results of a specific run.

In [30]:
random_1 = tf.random.Generator.from_seed(42)

random_2 = tf.random.Generator.from_seed(43)

# generates the total numbers in a single array & places them in shape
random_1 = random_1.normal((2,2))
random_2 = random_2.normal((2,2))

print(random_1, random_2, random_1 == random_2)

# change the shape of random_1

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False]])>)

## Uniform vs Normal Distribution

The probability of getting numbers near the mean is higher than getting numbers far from the mean. This is the reason why the normal distribution is also called the bell curve.

The uniform distribution is a probability distribution where all outcomes are equally likely. The normal distribution is a probability distribution where all outcomes are equally likely.

In [171]:
print(tf.random.uniform((1,)))
print(tf.random.normal((1,)))

tf.Tensor([0.4151367], shape=(1,), dtype=float32)
tf.Tensor([0.13536637], shape=(1,), dtype=float32)


# Shuffling Tensors
> Note: shuffles only the rows & not the columns!

This means that let's say we have a tensor of shape (3, 5, 2) then only the first 2 dimensions will be shuffled.

Columns will remain the same.

In [82]:
unshuffled_tensor = tf.random.Generator.from_seed(42)
unshuffled_tensor = unshuffled_tensor.normal((2,2,2))

print(unshuffled_tensor, "\n")

shuffled_tensor = tf.random.shuffle(unshuffled_tensor)

print(shuffled_tensor)

tf.Tensor(
[[[-0.7565803  -0.06854702]
  [ 0.07595026 -1.2573844 ]]

 [[-0.23193763 -1.8107855 ]
  [ 0.09988727 -0.50998646]]], shape=(2, 2, 2), dtype=float32) 

tf.Tensor(
[[[-0.23193763 -1.8107855 ]
  [ 0.09988727 -0.50998646]]

 [[-0.7565803  -0.06854702]
  [ 0.07595026 -1.2573844 ]]], shape=(2, 2, 2), dtype=float32)


# Other ways to create tensors

In [178]:
# create tensor of all ones
tf.ones((2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [179]:
tf.zeros((2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

## From numpy arrays

In [186]:
arr = np.arange(1, 25)

tf.constant(arr, shape=(6,2,2), dtype=tf.float32)

<tf.Tensor: shape=(6, 2, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]],

       [[13., 14.],
        [15., 16.]],

       [[17., 18.],
        [19., 20.]],

       [[21., 22.],
        [23., 24.]]], dtype=float32)>

# Indexing Tensors

In [256]:
random_r2_tensor = tf.random.Generator.from_seed(42).normal((2,3,4,3))

rank_2_tensor = tf.constant(random_r2_tensor)
# print(rank_2_tensor)

# get last 2 remaining elements from the columns (,,,3) dimension
# print(rank_2_tensor[:, :, :, 1:])

print(rank_2_tensor[:1])

# get first element from (2) dim, after 1 elements from (3) dim & first element from (4) dim
print(rank_2_tensor[:1, 1:, :1])

tf.Tensor(
[[[[-0.7565803  -0.06854702  0.07595026]
   [-1.2573844  -0.23193763 -1.8107855 ]
   [ 0.09988727 -0.50998646 -0.7535805 ]
   [-0.57166284  0.1480774  -0.23362993]]

  [[-0.3522796   0.40621263 -1.0523509 ]
   [ 1.2054597   1.6874489  -0.4462975 ]
   [-2.3410842   0.99009085 -0.0876323 ]
   [-0.635568   -0.6161736  -1.9441465 ]]

  [[-0.48293006 -0.52447474 -1.0345329 ]
   [ 1.3066901  -1.5184573  -0.4585211 ]
   [ 0.5714663  -1.5331722   0.45331386]
   [ 1.1487608  -1.2659091  -0.47450137]]]], shape=(1, 3, 4, 3), dtype=float32)
tf.Tensor(
[[[[-0.3522796   0.40621263 -1.0523509 ]]

  [[-0.48293006 -0.52447474 -1.0345329 ]]]], shape=(1, 2, 1, 3), dtype=float32)


# Expanding Tensors

The number of elements remain same, but the rank increases.

Using `tf.newaxis` or `tf.expand_dims` re-shapes the data so that there's a whole new dimension.

**For example:**
Adding a new dimension to the array `[1, 2, 3]` makes it `[ [1], [2], [3] ]` promoting the original array's shape from (3, ) to (3, 1) but the total number of elements remained same before i.e 3 and after i.e 3 * 1 = 3.

## `tf.newaxis`

In [270]:
r2_tensor = tf.random.Generator.from_seed(42).normal((3, 4, 2))

r3_tensor = r2_tensor[..., tf.newaxis] # shape = (3, 4, 2, 1)

r4_tensor = r3_tensor[..., tf.newaxis] # shape = (3, 4, 2, 1, 1)

print("Before:", r2_tensor, "\n")

print("After:", r3_tensor)

print("And after...", r4_tensor)

Before: tf.Tensor(
[[[-0.7565803  -0.06854702]
  [ 0.07595026 -1.2573844 ]
  [-0.23193763 -1.8107855 ]
  [ 0.09988727 -0.50998646]]

 [[-0.7535805  -0.57166284]
  [ 0.1480774  -0.23362993]
  [-0.3522796   0.40621263]
  [-1.0523509   1.2054597 ]]

 [[ 1.6874489  -0.4462975 ]
  [-2.3410842   0.99009085]
  [-0.0876323  -0.635568  ]
  [-0.6161736  -1.9441465 ]]], shape=(3, 4, 2), dtype=float32) 

After: tf.Tensor(
[[[[-0.7565803 ]
   [-0.06854702]]

  [[ 0.07595026]
   [-1.2573844 ]]

  [[-0.23193763]
   [-1.8107855 ]]

  [[ 0.09988727]
   [-0.50998646]]]


 [[[-0.7535805 ]
   [-0.57166284]]

  [[ 0.1480774 ]
   [-0.23362993]]

  [[-0.3522796 ]
   [ 0.40621263]]

  [[-1.0523509 ]
   [ 1.2054597 ]]]


 [[[ 1.6874489 ]
   [-0.4462975 ]]

  [[-2.3410842 ]
   [ 0.99009085]]

  [[-0.0876323 ]
   [-0.635568  ]]

  [[-0.6161736 ]
   [-1.9441465 ]]]], shape=(3, 4, 2, 1), dtype=float32)
And after... tf.Tensor(
[[[[[-0.7565803 ]]

   [[-0.06854702]]]


  [[[ 0.07595026]]

   [[-1.2573844 ]]]


  [[[

In [273]:
r2_tensor = tf.random.Generator.from_seed(42).normal((3, 4))

r4_tensor = r2_tensor[:, tf.newaxis, :, tf.newaxis] # shape = (3, 1, 4, 1)

r2_tensor, r4_tensor

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 1, 4, 1), dtype=float32, numpy=
 array([[[[-0.7565803 ],
          [-0.06854702],
          [ 0.07595026],
          [-1.2573844 ]]],
 
 
        [[[-0.23193763],
          [-1.8107855 ],
          [ 0.09988727],
          [-0.50998646]]],
 
 
        [[[-0.7535805 ],
          [-0.57166284],
          [ 0.1480774 ],
          [-0.23362993]]]], dtype=float32)>)

## `tf.expand_dims()`

In [281]:
r2_tensor = tf.random.Generator.from_seed(42).normal((3, 4))

# insert new axis in last
r3_tensor = tf.expand_dims(r2_tensor, -1) # shape = (3, 4, ->1<-)

# insert new axis at 1th position
r3_tensor_2 = tf.expand_dims(r2_tensor, axis=1) # shape = (3, ->1<-, 4)

print(f"r3_tensor shape: {r3_tensor.shape}")
print(f"r3_tensor_2 shape: {r3_tensor_2.shape}")

r3_tensor shape: (3, 4, 1)
r3_tensor_2 shape: (3, 1, 4)
