In [2]:
import tensorflow as tf
import numpy as np

# Manipulating Tensors

## Element-wise operations

In [3]:
ts = tf.constant([
    [10, 20],
    [30, 40]
])

print(ts + 5)
print(ts * 10)
print(ts - 5)

tf.Tensor(
[[15 25]
 [35 45]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100 200]
 [300 400]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 15]
 [25 35]], shape=(2, 2), dtype=int32)


In [4]:
new_ts = tf.multiply(ts, 10) # performance benefits for using tf.add/subtract etc. over +/- etc.

new_ts

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 200],
       [300, 400]], dtype=int32)>

## Matrix Multiplication

In [5]:
m1 = tf.constant([
    [1,2,3],
    [4,5,6]
])

m2 = tf.constant([
    [2,4,1],
    [8,16,1],
    [32,64,1]
])

tf.matmul(m1, m2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[114, 228,   6],
       [240, 480,  15]], dtype=int32)>

In [6]:
m1 @ m2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[114, 228,   6],
       [240, 480,  15]], dtype=int32)>

### Reshaping Tensors

In [7]:
X = tf.constant([
    [7, 8],
    [9, 10],
    [11, 12]
])

Y = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(X.shape, Y.shape)

# print(tf.matmul(X, Y)) # matrix size incompatible error

# 2 * 3 OR 3 * 2 = 6 reshaping can be done as long as the new shape has equal elements as before
Y = tf.reshape(Y, shape=(2, 3))

print(f"New shape of Y is: {Y}\n")

print(tf.matmul(X, Y))

(3, 2) (3, 2)
New shape of Y is: [[1 2 3]
 [4 5 6]]

tf.Tensor(
[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]], shape=(3, 3), dtype=int32)


### Transposing Tensors

Matrix transpose operation flips the axes of the elements in a tensor.

In [8]:
X = tf.constant([
    [7, 8],
    [9, 10],
    [11, 12]
])

tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

### Dot product

these can be used:
- `tf.matmul()`
- `tf.tensordot()`

In [9]:
tf.matmul(X, Y), tf.tensordot(X, Y, axes=1)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 39,  54,  69],
        [ 49,  68,  87],
        [ 59,  82, 105]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 39,  54,  69],
        [ 49,  68,  87],
        [ 59,  82, 105]], dtype=int32)>)

## Tensor Type Casting

In [14]:
X = tf.constant([
    [7, 8],
    [9, 10],
    [11, 12]
])

X_f32 = tf.cast(X, dtype=tf.float32)

X_f32

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 7.,  8.],
       [ 9., 10.],
       [11., 12.]], dtype=float32)>

## Aggregating Tensors

In [54]:
X = tf.random.Generator.from_seed(42).uniform((50,), -100, 100, dtype=tf.int32)
print("Tensor", X, "\n")

# Absolute value
print("Absolute", tf.abs(X), "\n")

# Min
print("Min", tf.reduce_min(X).numpy())

# Max
print("Max", tf.reduce_max(X).numpy())

# Mean
print("Mean", tf.reduce_mean(X).numpy())

# Variance
print("Variance", tf.math.reduce_variance(tf.cast(X, tf.float32)).numpy())

# Standard Deviation
print("Std", tf.math.reduce_std(tf.cast(X, tf.float32)).numpy())

# positional max
print(f"the max value {tf.reduce_max(X).numpy()} lies at index {tf.argmax(X).numpy()}")

Tensor tf.Tensor(
[  3  -3 -74  98 -74 -19  71  27  42   7  31  86 -80 -47  15 -38  28  53
 -74  47  63  69 -62  29 -86   9 -34 -43 -75  14 -76  83  60   8 -75 -44
  35 -39 -20 -55 -76  76 -92 -50  81  12 -76  88 -71  -8], shape=(50,), dtype=int32) 

Absolute tf.Tensor(
[ 3  3 74 98 74 19 71 27 42  7 31 86 80 47 15 38 28 53 74 47 63 69 62 29
 86  9 34 43 75 14 76 83 60  8 75 44 35 39 20 55 76 76 92 50 81 12 76 88
 71  8], shape=(50,), dtype=int32) 

Min -92
Max 98
Mean -5
Variance 3294.9055
Std 57.401268
the max value 98 lies at index 3


## Squeezing Tensors

`tf.squeeze(tensor)` removes all the single dimensions and returns a tensor with all the dimensions of length 1 removed.

In [57]:
X = tf.random.Generator.from_seed(42).uniform((50,))
X = tf.constant(X, shape=(1,1,1,1,50))

X

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.7493447 , 0.73561966, 0.45230794, 0.49039817, 0.1889317 ,
           0.52027524, 0.8736881 , 0.46921718, 0.63932586, 0.6467117 ,
           0.96246755, 0.41009164, 0.86540747, 0.8862978 , 0.27795732,
           0.8857763 , 0.2179842 , 0.29115117, 0.03953862, 0.8136791 ,
           0.8139852 , 0.52180684, 0.12496924, 0.5488483 , 0.7755773 ,
           0.6184403 , 0.24936223, 0.89341843, 0.28422844, 0.70332646,
           0.2622137 , 0.4432162 , 0.466465  , 0.05981874, 0.40098202,
           0.69292355, 0.1284684 , 0.22770369, 0.33691216, 0.5329138 ,
           0.5914326 , 0.21738243, 0.5322075 , 0.05148339, 0.03951418,
           0.41866875, 0.78939915, 0.04384279, 0.96955836, 0.49116182]]]]],
      dtype=float32)>

In [62]:
X = tf.reshape(X, (25,1,1,1,1,2))

print("Un-squeezed", X)

X_squeezed = tf.squeeze(X)

print("squeezed", X_squeezed)

Un-squeezed tf.Tensor(
[[[[[[0.7493447  0.73561966]]]]]




 [[[[[0.45230794 0.49039817]]]]]




 [[[[[0.1889317  0.52027524]]]]]




 [[[[[0.8736881  0.46921718]]]]]




 [[[[[0.63932586 0.6467117 ]]]]]




 [[[[[0.96246755 0.41009164]]]]]




 [[[[[0.86540747 0.8862978 ]]]]]




 [[[[[0.27795732 0.8857763 ]]]]]




 [[[[[0.2179842  0.29115117]]]]]




 [[[[[0.03953862 0.8136791 ]]]]]




 [[[[[0.8139852  0.52180684]]]]]




 [[[[[0.12496924 0.5488483 ]]]]]




 [[[[[0.7755773  0.6184403 ]]]]]




 [[[[[0.24936223 0.89341843]]]]]




 [[[[[0.28422844 0.70332646]]]]]




 [[[[[0.2622137  0.4432162 ]]]]]




 [[[[[0.466465   0.05981874]]]]]




 [[[[[0.40098202 0.69292355]]]]]




 [[[[[0.1284684  0.22770369]]]]]




 [[[[[0.33691216 0.5329138 ]]]]]




 [[[[[0.5914326  0.21738243]]]]]




 [[[[[0.5322075  0.05148339]]]]]




 [[[[[0.03951418 0.41866875]]]]]




 [[[[[0.78939915 0.04384279]]]]]




 [[[[[0.96955836 0.49116182]]]]]], shape=(25, 1, 1, 1, 1, 2), dtype=float32)
squeezed tf.

# GPUs

Google colab provides access to different runtimes including CUDA enabled GPUs & Google's own TPUs for free.

In [66]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]